In [ ]:
# Activity 2.09

In [1]:
from sqlalchemy import create_engine
import pandas as pd
import getpass  # To get the password without showing the input
password = getpass.getpass()

········

In [ ]:
connection_string = 'mysql+pymysql://root:' + password + '@localhost/bank'
engine = create_engine(connection_string)

In [5]:
# Activity 1:
#1 & #2
result = engine.execute('SELECT * FROM bank.loan where status = \'A\' or status = \'B\'')
for row in result:
    print(row)

(5314, 1787, 930705, 96396, 12, 8033.0, 'B', 'Defaulter - Contract Finished')
(5316, 1801, 930711, 165960, 36, 4610.0, 'A', 'Good - Contract Finished')
(6863, 9188, 930728, 127080, 60, 2118.0, 'A', 'Good - Contract Finished')
(5325, 1843, 930803, 105804, 36, 2939.0, 'A', 'Good - Contract Finished')
(7240, 11013, 930906, 274740, 60, 4579.0, 'A', 'Good - Contract Finished')
(6687, 8261, 930913, 87840, 24, 3660.0, 'A', 'Good - Contract Finished')
(7284, 11265, 930915, 52788, 12, 4399.0, 'A', 'Good - Contract Finished')
(6111, 5428, 930924, 174744, 24, 7281.0, 'B', 'Defaulter - Contract Finished')
(7235, 10973, 931013, 154416, 48, 3217.0, 'A', 'Good - Contract Finished')
(5997, 4894, 931104, 117024, 24, 4876.0, 'A', 'Good - Contract Finished')
(7121, 10364, 931110, 21924, 36, 609.0, 'A', 'Good - Contract Finished')
(6077, 5270, 931122, 79608, 24, 3317.0, 'A', 'Good - Contract Finished')
(6228, 6034, 931201, 464520, 60, 7742.0, 'B', 'Defaulter - Contract Finished')
(6356, 6701, 931208, 95400, 36, 2650.0, 'A', 'Good - Contract Finished')
(5523, 2705, 931208, 93888, 36, 2608.0, 'A', 'Good - Contract Finished')
(6456, 7123, 931209, 47016, 12, 3918.0, 'A', 'Good - Contract Finished')
(7104, 10320, 931213, 259740, 60, 4329.0, 'A', 'Good - Contract Finished')
(6820, 9034, 931216, 38148, 12, 3179.0, 'A', 'Good - Contract Finished')
(6876, 9236, 931221, 86616, 12, 7218.0, 'A', 'Good - Contract Finished')
(7097, 10266, 931223, 75624, 24, 3151.0, 'B', 'Defaulter - Contract Finished')
(4959, 2, 940105, 80952, 24, 3373.0, 'A', 'Good - Contract Finished')
(6499, 7401, 940105, 80952, 24, 3373.0, 'A', 'Good - Contract Finished')
(5479, 2486, 940110, 24516, 12, 2043.0, 'A', 'Good - Contract Finished')
(6721, 8475, 940121, 21072, 24, 878.0, 'A', 'Good - Contract Finished')
(7259, 11111, 940131, 108144, 36, 3004.0, 'A', 'Good - Contract Finished')
(5285, 1603, 940206, 78936, 12, 6578.0, 'A', 'Good - Contract Finished')
(5189, 1166, 940207, 149040, 48, 3105.0, 'A', 'Good - Contract Finished')
(6650, 8073, 940217, 49320, 12, 4110.0, 'B', 'Defaulter - Contract Finished')
(7226, 10940, 940223, 197748, 36, 5493.0, 'A', 'Good - Contract Finished')
(7262, 11135, 940301, 182628, 36, 5073.0, 'A', 'Good - Contract Finished')
(5519, 2694, 940308, 91632, 12, 7636.0, 'A', 'Good - Contract Finished')
(6577, 7753, 940311, 51696, 24, 2154.0, 'A', 'Good - Contract Finished')
(6509, 7445, 940315, 55368, 24, 2307.0, 'A', 'Good - Contract Finished')
(6520, 7485, 940316, 91200, 24, 3800.0, 'A', 'Good - Contract Finished')
(6699, 8330, 940330, 7656, 24, 319.0, 'A', 'Good - Contract Finished')
(6336, 6555, 940331, 212400, 36, 5900.0, 'A', 'Good - Contract Finished')
(6202, 5891, 940418, 65184, 12, 5432.0, 'A', 'Good - Contract Finished')
(7066, 10131, 940502, 215388, 36, 5983.0, 'B', 'Defaulter - Contract Finished')
(6072, 5256, 940510, 193968, 36, 5388.0, 'A', 'Good - Contract Finished')
(5130, 813, 940511, 24312, 12, 2026.0, 'A', 'Good - Contract Finished')
(6678, 8173, 940520, 80340, 12, 6695.0, 'A', 'Good - Contract Finished')
(6998, 9833, 940521, 97632, 12, 8136.0, 'A', 'Good - Contract Finished')
(6580, 7769, 940522, 196080, 48, 4085.0, 'A', 'Good - Contract Finished')
(6316, 6473, 940526, 76908, 12, 6409.0, 'B', 'Defaulter - Contract Finished')
(6512, 7454, 940526, 63312, 48, 1319.0, 'A', 'Good - Contract Finished')
(6407, 6930, 940526, 25944, 24, 1081.0, 'A', 'Good - Contract Finished')
(5002, 173, 940531, 104808, 12, 8734.0, 'A', 'Good - Contract Finished')
(6647, 8051, 940601, 208320, 48, 4340.0, 'A', 'Good - Contract Finished')
(7137, 10439, 940603, 151560, 24, 6315.0, 'A', 'Good - Contract Finished')
(6903, 9337, 940604, 52128, 24, 2172.0, 'A', 'Good - Contract Finished')
(5918, 4576, 940604, 300204, 36, 8339.0, 'A', 'Good - Contract Finished')
(6642, 8027, 940605, 77640, 12, 6470.0, 'A', 'Good - Contract Finished')
(6210, 5927, 940606, 87216, 48, 1817.0, 'B', 'Defaulter - Contract Finished')
(6279, 6273, 940607, 87360, 24, 3640.0, 'A', 'Good - Contract Finished')
(7249, 11065, 940612, 69360, 48, 1445.0, 'A', 'Good - Contract Finished')
(6112, 5442, 940617, 174744, 24, 7281.0, 'B', 'Defaulter - Contract Finished')
(6596, 7844, 940625, 91584, 24, 3816.0, 'A', 'Good - Contract Finished')
(5657, 3354, 940705, 4980, 12, 415.0, 'A', 'Good - Contract Finished')
(5533, 2762, 940705, 111384, 24, 4641.0, 'A', 'Good - Contract Finished')
(6232, 6051, 940708, 276660, 36, 7685.0, 'B', 'Defaulter - Contract Finished')
(6888, 9265, 940711, 39576, 12, 3298.0, 'A', 'Good - Contract Finished')
(6066, 5228, 940711, 173808, 24, 7242.0, 'A', 'Good - Contract Finished')
(6004, 4937, 940723, 143904, 24, 5996.0, 'A', 'Good - Contract Finished')
(5126, 790, 940724, 208128, 48, 4336.0, 'B', 'Defaulter - Contract Finished')
(7220, 10911, 940728, 131292, 36, 3647.0, 'A', 'Good - Contract Finished')
(6668, 8129, 940730, 74736, 36, 2076.0, 'A', 'Good - Contract Finished')
(5395, 2176, 940730, 299088, 36, 8308.0, 'B', 'Defaulter - Contract Finished')
(6064, 5215, 940804, 14628, 12, 1219.0, 'A', 'Good - Contract Finished')
(6919, 9403, 940805, 120888, 36, 3358.0, 'A', 'Good - Contract Finished')
(6841, 9104, 940807, 172080, 48, 3585.0, 'A', 'Good - Contract Finished')
(6038, 5120, 940810, 323472, 48, 6739.0, 'A', 'Good - Contract Finished')
(6729, 8519, 940811, 74688, 12, 6224.0, 'A', 'Good - Contract Finished')
(7198, 10788, 940823, 45768, 12, 3814.0, 'A', 'Good - Contract Finished')
(6686, 8260, 940825, 224604, 36, 6239.0, 'A', 'Good - Contract Finished')
(5836, 4259, 940827, 79632, 24, 3318.0, 'A', 'Good - Contract Finished')
(7061, 10105, 940827, 121896, 24, 5079.0, 'A', 'Good - Contract Finished')
(5595, 3050, 940902, 82896, 12, 6908.0, 'A', 'Good - Contract Finished')
(5723, 3674, 940910, 23628, 12, 1969.0, 'A', 'Good - Contract Finished')
(6120, 5481, 940911, 209184, 48, 4358.0, 'A', 'Good - Contract Finished')
(6895, 9307, 940919, 41904, 12, 3492.0, 'A', 'Good - Contract Finished')
(5882, 4427, 940926, 87816, 12, 7318.0, 'A', 'Good - Contract Finished')
(5754, 3834, 940928, 23052, 12, 1921.0, 'A', 'Good - Contract Finished')
(6594, 7824, 940928, 189696, 24, 7904.0, 'B', 'Defaulter - Contract Finished')
(6738, 8566, 940929, 230220, 36, 6395.0, 'B', 'Defaulter - Contract Finished')
(6624, 7965, 940930, 71460, 12, 5955.0, 'A', 'Good - Contract Finished')
(6216, 5952, 940930, 141240, 24, 5885.0, 'A', 'Good - Contract Finished')
(6229, 6040, 941002, 11736, 24, 489.0, 'A', 'Good - Contract Finished')
(5887, 4448, 941003, 192744, 36, 5354.0, 'A', 'Good - Contract Finished')
(6808, 8982, 941012, 227880, 36, 6330.0, 'A', 'Good - Contract Finished')
(6297, 6363, 941025, 17508, 12, 1459.0, 'A', 'Good - Contract Finished')
(5161, 1012, 941028, 98184, 24, 4091.0, 'A', 'Good - Contract Finished')
(5390, 2167, 941030, 170256, 24, 7094.0, 'A', 'Good - Contract Finished')
(6150, 5622, 941102, 83016, 12, 6918.0, 'A', 'Good - Contract Finished')
(6223, 5991, 941103, 61056, 48, 1272.0, 'A', 'Good - Contract Finished')
(5032, 290, 941103, 123696, 48, 2577.0, 'A', 'Good - Contract Finished')
(6253, 6148, 941104, 59760, 24, 2490.0, 'A', 'Good - Contract Finished')
(6460, 7133, 941106, 48672, 36, 1352.0, 'A', 'Good - Contract Finished')
(6645, 8041, 941106, 140400, 36, 3900.0, 'A', 'Good - Contract Finished')
(5176, 1106, 941112, 192552, 24, 8023.0, 'B', 'Defaulter - Contract Finished')
(5269, 1527, 941119, 164052, 36, 4557.0, 'B', 'Defaulter - Contract Finished')
(5351, 1978, 941204, 205200, 36, 5700.0, 'A', 'Good - Contract Finished')
(5861, 4337, 941208, 51408, 24, 2142.0, 'A', 'Good - Contract Finished')
(6306, 6425, 941220, 36684, 12, 3057.0, 'A', 'Good - Contract Finished')
(5576, 2962, 941221, 31248, 12, 2604.0, 'A', 'Good - Contract Finished')
(7192, 10738, 941221, 115992, 36, 3222.0, 'A', 'Good - Contract Finished')
(5739, 3747, 950102, 76380, 12, 6365.0, 'A', 'Good - Contract Finished')
(6526, 7523, 950103, 288468, 36, 8013.0, 'A', 'Good - Contract Finished')
(6244, 6118, 950108, 270648, 36, 7518.0, 'B', 'Defaulter - Contract Finished')
(5131, 816, 950108, 48624, 24, 2026.0, 'A', 'Good - Contract Finished')
(6960, 9640, 950111, 76416, 24, 3184.0, 'A', 'Good - Contract Finished')
(6598, 7857, 950118, 68112, 12, 5676.0, 'A', 'Good - Contract Finished')
(5464, 2419, 950130, 95808, 12, 7984.0, 'A', 'Good - Contract Finished')
(6315, 6472, 950206, 43164, 12, 3597.0, 'A', 'Good - Contract Finished')
(5877, 4414, 950223, 97224, 24, 4051.0, 'A', 'Good - Contract Finished')
(6227, 6030, 950304, 28248, 24, 1177.0, 'A', 'Good - Contract Finished')
(7241, 11021, 950304, 168984, 24, 7041.0, 'B', 'Defaulter - Contract Finished')
(6737, 8564, 950311, 76680, 24, 3195.0, 'A', 'Good - Contract Finished')
(6694, 8316, 950319, 134784, 24, 5616.0, 'A', 'Good - Contract Finished')
(5599, 3064, 950321, 15420, 12, 1285.0, 'A', 'Good - Contract Finished')
(6546, 7607, 950327, 31728, 24, 1322.0, 'A', 'Good - Contract Finished')
(5453, 2361, 950401, 156672, 36, 4352.0, 'A', 'Good - Contract Finished')
(5740, 3752, 950402, 18564, 12, 1547.0, 'A', 'Good - Contract Finished')
(6745, 8625, 950410, 47304, 24, 1971.0, 'A', 'Good - Contract Finished')
(6950, 9591, 950411, 104712, 24, 4363.0, 'A', 'Good - Contract Finished')
(6996, 9828, 950413, 126600, 24, 5275.0, 'A', 'Good - Contract Finished')
(5352, 1993, 950415, 68400, 12, 5700.0, 'B', 'Defaulter - Contract Finished')
(5310, 1762, 950428, 248148, 36, 6893.0, 'A', 'Good - Contract Finished')
(5045, 347, 950501, 187224, 24, 7801.0, 'B', 'Defaulter - Contract Finished')
(6929, 9472, 950508, 36396, 12, 3033.0, 'A', 'Good - Contract Finished')
(5212, 1256, 950529, 71064, 36, 1974.0, 'A', 'Good - Contract Finished')
(6676, 8159, 950613, 29784, 24, 1241.0, 'A', 'Good - Contract Finished')
(6965, 9656, 950613, 139536, 24, 5814.0, 'A', 'Good - Contract Finished')
(6725, 8489, 950623, 265320, 36, 7370.0, 'A', 'Good - Contract Finished')
(7166, 10630, 950624, 198240, 24, 8260.0, 'A', 'Good - Contract Finished')
(6157, 5650, 950710, 98592, 24, 4108.0, 'A', 'Good - Contract Finished')
(5693, 3489, 950801, 44088, 24, 1837.0, 'A', 'Good - Contract Finished')
(5922, 4580, 950805, 20220, 12, 1685.0, 'A', 'Good - Contract Finished')
(5959, 4727, 950811, 107640, 24, 4485.0, 'A', 'Good - Contract Finished')
(5980, 4825, 950818, 21396, 12, 1783.0, 'A', 'Good - Contract Finished')
(5237, 1375, 950829, 45336, 24, 1889.0, 'A', 'Good - Contract Finished')
(7008, 9897, 950922, 36168, 12, 3014.0, 'A', 'Good - Contract Finished')
(6600, 7861, 951008, 21852, 36, 607.0, 'A', 'Good - Contract Finished')
(7057, 10093, 951020, 231696, 36, 6436.0, 'A', 'Good - Contract Finished')
(7176, 10663, 951028, 260028, 36, 7223.0, 'A', 'Good - Contract Finished')
(6362, 6738, 951031, 37908, 12, 3159.0, 'A', 'Good - Contract Finished')
(5880, 4423, 951031, 73836, 36, 2051.0, 'A', 'Good - Contract Finished')
(6535, 7546, 951102, 41952, 12, 3496.0, 'A', 'Good - Contract Finished')
(5449, 2343, 951104, 99336, 24, 4139.0, 'A', 'Good - Contract Finished')
(6342, 6609, 951112, 60156, 36, 1671.0, 'B', 'Defaulter - Contract Finished')
(6985, 9731, 951122, 113796, 36, 3161.0, 'A', 'Good - Contract Finished')
(5805, 4081, 951128, 137904, 24, 5746.0, 'B', 'Defaulter - Contract Finished')
(6185, 5774, 951128, 31176, 24, 1299.0, 'A', 'Good - Contract Finished')
(7243, 11042, 951204, 217152, 36, 6032.0, 'A', 'Good - Contract Finished')
(6578, 7765, 951211, 27984, 12, 2332.0, 'A', 'Good - Contract Finished')
(5413, 2227, 951212, 92976, 24, 3874.0, 'A', 'Good - Contract Finished')
(6949, 9583, 951212, 104712, 24, 4363.0, 'A', 'Good - Contract Finished')
(6589, 7815, 960101, 189696, 24, 7904.0, 'A', 'Good - Contract Finished')
(7263, 11138, 960119, 89880, 24, 3745.0, 'A', 'Good - Contract Finished')
(5750, 3804, 960208, 63252, 12, 5271.0, 'A', 'Good - Contract Finished')
(6027, 5066, 960210, 61656, 24, 2569.0, 'B', 'Defaulter - Contract Finished')
(6303, 6400, 960212, 72408, 24, 3017.0, 'B', 'Defaulter - Contract Finished')
(6137, 5574, 960410, 44628, 12, 3719.0, 'A', 'Good - Contract Finished')
(6501, 7418, 960429, 30276, 12, 2523.0, 'B', 'Defaulter - Contract Finished')
(4961, 19, 960429, 30276, 12, 2523.0, 'B', 'Defaulter - Contract Finished')
(4973, 67, 960502, 165960, 24, 6915.0, 'A', 'Good - Contract Finished')
(5892, 4462, 960514, 66480, 24, 2770.0, 'B', 'Defaulter - Contract Finished')
(5445, 2322, 960629, 46320, 24, 1930.0, 'A', 'Good - Contract Finished')
(6667, 8127, 960715, 155880, 24, 6495.0, 'A', 'Good - Contract Finished')
(6019, 5033, 960725, 11400, 12, 950.0, 'A', 'Good - Contract Finished')
(5136, 846, 960728, 187104, 24, 7796.0, 'A', 'Good - Contract Finished')
(6471, 7184, 960804, 155640, 24, 6485.0, 'A', 'Good - Contract Finished')
(7305, 11359, 960806, 54024, 12, 4502.0, 'A', 'Good - Contract Finished')
(6144, 5593, 960809, 44376, 12, 3698.0, 'A', 'Good - Contract Finished')
(5088, 544, 960822, 91152, 24, 3798.0, 'A', 'Good - Contract Finished')
(5988, 4851, 960822, 141648, 24, 5902.0, 'A', 'Good - Contract Finished')
(6865, 9199, 960911, 29448, 12, 2454.0, 'B', 'Defaulter - Contract Finished')
(6613, 7926, 960922, 84120, 24, 3505.0, 'A', 'Good - Contract Finished')
(5897, 4476, 960925, 15192, 24, 633.0, 'A', 'Good - Contract Finished')
(6995, 9814, 960926, 96168, 12, 8014.0, 'A', 'Good - Contract Finished')
(5375, 2106, 961003, 101520, 12, 8460.0, 'A', 'Good - Contract Finished')
(6644, 8039, 961020, 93600, 24, 3900.0, 'A', 'Good - Contract Finished')
(6921, 9422, 961029, 86184, 12, 7182.0, 'A', 'Good - Contract Finished')
(5366, 2062, 961029, 86184, 12, 7182.0, 'A', 'Good - Contract Finished')
(5741, 3754, 961103, 68544, 24, 2856.0, 'A', 'Good - Contract Finished')
(4996, 132, 961106, 88440, 12, 7370.0, 'A', 'Good - Contract Finished')
(6015, 5001, 961109, 110112, 24, 4588.0, 'A', 'Good - Contract Finished')
(6309, 6434, 961111, 110136, 24, 4589.0, 'A', 'Good - Contract Finished')
(6599, 7859, 961119, 72120, 12, 6010.0, 'A', 'Good - Contract Finished')
(5388, 2153, 961128, 61560, 12, 5130.0, 'A', 'Good - Contract Finished')
(7130, 10411, 961211, 123408, 24, 5142.0, 'A', 'Good - Contract Finished')
(7308, 11362, 961227, 129408, 24, 5392.0, 'A', 'Good - Contract Finished')
(5358, 2018, 970121, 38520, 12, 3210.0, 'A', 'Good - Contract Finished')
(6878, 9242, 970124, 23184, 12, 1932.0, 'A', 'Good - Contract Finished')
(5134, 825, 970202, 53076, 12, 4423.0, 'A', 'Good - Contract Finished')
(6934, 9494, 970209, 116832, 12, 9736.0, 'A', 'Good - Contract Finished')
(5682, 3455, 970307, 67464, 12, 5622.0, 'A', 'Good - Contract Finished')
(7201, 10807, 970307, 67464, 12, 5622.0, 'A', 'Good - Contract Finished')
(6377, 6792, 970317, 17184, 12, 1432.0, 'A', 'Good - Contract Finished')
(5992, 4863, 970318, 76080, 12, 6340.0, 'A', 'Good - Contract Finished')
(6753, 8688, 970320, 67980, 12, 5665.0, 'A', 'Good - Contract Finished')
(7046, 10049, 970328, 91632, 12, 7636.0, 'A', 'Good - Contract Finished')
(5868, 4361, 970329, 90156, 12, 7513.0, 'A', 'Good - Contract Finished')
(5878, 4415, 970401, 74040, 12, 6170.0, 'A', 'Good - Contract Finished')
(5005, 176, 970410, 27456, 12, 2288.0, 'A', 'Good - Contract Finished')
(7253, 11079, 970426, 98304, 12, 8192.0, 'A', 'Good - Contract Finished')
(5634, 3229, 970501, 39024, 12, 3252.0, 'A', 'Good - Contract Finished')
(6887, 9263, 970508, 39576, 12, 3298.0, 'A', 'Good - Contract Finished')
(7119, 10361, 970602, 86880, 12, 7240.0, 'A', 'Good - Contract Finished')
(6621, 7957, 970614, 42900, 12, 3575.0, 'A', 'Good - Contract Finished')
(6310, 6440, 970617, 34572, 12, 2881.0, 'A', 'Good - Contract Finished')
(5932, 4626, 970618, 33348, 12, 2779.0, 'A', 'Good - Contract Finished')
(6942, 9513, 970716, 18324, 12, 1527.0, 'A', 'Good - Contract Finished')
(7051, 10068, 970728, 77808, 12, 6484.0, 'A', 'Good - Contract Finished')
(6758, 8742, 970729, 33144, 12, 2762.0, 'A', 'Good - Contract Finished')
(5377, 2116, 970804, 92400, 12, 7700.0, 'A', 'Good - Contract Finished')
(5856, 4320, 970809, 51360, 12, 4280.0, 'B', 'Defaulter - Contract Finished')
(4986, 97, 970810, 102876, 12, 8573.0, 'A', 'Good - Contract Finished')
(5117, 718, 970820, 76944, 12, 6412.0, 'A', 'Good - Contract Finished')
(5638, 3249, 970827, 68124, 12, 5677.0, 'A', 'Good - Contract Finished')
(5338, 1888, 970830, 57360, 12, 4780.0, 'B', 'Defaulter - Contract Finished')
(6612, 7907, 970831, 97392, 12, 8116.0, 'A', 'Good - Contract Finished')
(5718, 3637, 970901, 14028, 12, 1169.0, 'A', 'Good - Contract Finished')
(5229, 1329, 970906, 23520, 12, 1960.0, 'A', 'Good - Contract Finished')
(5643, 3273, 970921, 94512, 12, 7876.0, 'B', 'Defaulter - Contract Finished')
(7264, 11141, 971007, 44940, 12, 3745.0, 'A', 'Good - Contract Finished')
(7277, 11231, 971024, 89280, 12, 7440.0, 'A', 'Good - Contract Finished')
(5398, 2187, 971104, 53472, 12, 4456.0, 'A', 'Good - Contract Finished')
(5103, 666, 971128, 12540, 12, 1045.0, 'A', 'Good - Contract Finished')
(6502, 7424, 971208, 30276, 12, 2523.0, 'A', 'Good - Contract Finished')
(5651, 3329, 971208, 19248, 12, 1604.0, 'A', 'Good - Contract Finished')
(4962, 25, 971208, 30276, 12, 2523.0, 'A', 'Good - Contract Finished')
(7199, 10789, 971209, 45768, 12, 3814.0, 'A', 'Good - Contract Finished')
(6727, 8505, 971210, 42840, 12, 3570.0, 'A', 'Good - Contract Finished')
(6059, 5196, 971228, 79824, 12, 6652.0, 'A', 'Good - Contract Finished')

In [7]:
# Activity 2:
#First query
data = pd.read_sql_query('select count(acc.account_id)  as Number_of_Accounts, year(acc.date) as Year, dis.A2 as District \
from bank.account as acc \
inner join bank.district as dis \
on acc.district_id = dis.A1 \
group by year(acc.date), dis.A2 \
order by Year, Number_of_Accounts DESC;', engine)
data.head()

   Number_of_Accounts  Year         District
0                 144  1993      Hl.m. Praha
1                  39  1993          Karvina
2                  38  1993  Ostrava - mesto
3                  27  1993     Brno - mesto
4                  26  1993          Olomouc

In [8]:
#second query
data = pd.read_sql_query('select sum(loa.amount) as Total_amount, round(avg(loa.amount),0) as Average_Amount, dis.A2 as "District", rank() over (order by sum(loa.amount) DESC) as "Rank" \
from bank.account as acc \
inner join bank.district as dis \
inner join bank.loan as loa \
on acc.account_id = loa.account_id and acc.district_id = dis.A1 \
group by dis.A2 \
order by Total_amount DESC;', engine)
data.head()

   Total_amount  Average_Amount         District  Rank
0    12932412.0        127200.0      Hl.m. Praha     1
1     4049400.0        127200.0     Brno - mesto     2
2     3260220.0        127200.0  Ostrava - mesto     3
3     3059820.0        127200.0          Karvina     4
4     3012768.0        127200.0             Zlin     5

In [ ]:
# Activity 3:
#1 Analyse:

In [ ]:
# Activity 4: